In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/gm_100_samarth_python.csv')

In [ ]:
df.head()

,Name,Ticker,sub_sector,market_cap,close_price,pe_ratio,5year_past_growth,1year_future_growth,total_revenue,PBT,...,percentage_upside,pat,outstanding_shares,eps,percentage_hold_by_promoter,analyst_buy_ratio,roe,profit_margin,ps_ratio,retail_holding_change
0,Reliance Industries Ltd,RELIANCE,Oil & Gas - Refining & Marketing,1.778090e+06,2712.20,29.290670,17.936498,30.535512,718061.00,84142.00,...,3.163484,60705.00,1.717385e+06,0.04,0.00,31.0,9.23,8.45,2.476238,0.000778
1,Tata Consultancy Services Ltd,TCS,IT Services & Consulting,1.241655e+06,3397.35,32.396353,9.886696,13.295058,195772.00,51687.00,...,1.549737,38327.00,1.203328e+06,0.03,0.00,41.0,24.34,19.58,6.342352,0.258454
2,HDFC Bank Ltd,HDFCBANK,Private Banks,8.917948e+05,1597.85,23.435750,14.242193,-27.600817,167695.40,50873.38,...,14.215978,38052.75,8.537420e+05,0.04,-0.01,37.0,29.35,22.69,5.317944,-0.299827
3,Infosys Ltd,INFY,IT Services & Consulting,6.806679e+05,1629.05,30.785523,11.618708,18.128913,123936.00,30110.00,...,2.974126,22110.00,6.585579e+05,0.03,0.00,42.0,21.71,17.84,5.492092,-8.934226
4,ICICI Bank Ltd,ICICIBANK,Private Banks,6.533383e+05,946.75,26.018932,6.796088,-49.983642,157536.32,34241.28,...,14.496963,25110.11,6.282281e+05,0.04,0.00,40.0,18.96,15.94,4.147223,-0.285631

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name                         4525 non-null   object
 1   Ticker                       4525 non-null   object
 2   sub_sector                   4525 non-null   object
 3   market_cap                   4426 non-null   float64
 4   close_price                  4426 non-null   float64
 5   pe_ratio                     4426 non-null   float64
 6   5year_past_growth            4426 non-null   float64
 7   1year_future_growth          4426 non-null   float64
 8   total_revenue                4426 non-null   float64
 9   PBT                          4426 non-null   float64
 10  Taxes_others                 4426 non-null   float64
 11  dii_holding                  4426 non-null   float64
 12  fii_holding                  4426 non-null   float64
 13  mf_holding                   4426 non-null   float64
 14  promoter_holding             4426 non-null   float64
 15  percentage_buy               4426 non-null   float64
 16  no_analyst_rec               4525 non-null   int64
 17  percentage_upside            4426 non-null   float64
 18  pat                          4426 non-null   float64
 19  outstanding_shares           4426 non-null   float64
 20  eps                          4383 non-null   float64
 21  percentage_hold_by_promoter  4353 non-null   float64
 22  analyst_buy_ratio            761 non-null    float64
 23  roe                          4246 non-null   float64
 24  profit_margin                4246 non-null   object
 25  ps_ratio                     4379 non-null   float64
 26  retail_holding_change        4426 non-null   float64
dtypes: float64(22), int64(1), object(4)
memory usage: 954.6+ KB

In [ ]:
df['no_analyst_rec'].unique()

array([24, 21, 34, 39, 28, 40,  0, 31, 16,  9,  2, 26, 15, 35, 32,  6, 33,
       37, 20, 18,  4, 22, 17,  1,  3, 19, 30,  8,  7, 29, 27, 13, 12, 23,
       11, 10, 25,  5, 14])

In [ ]:
# This code is to fill the null values
df['no_analyst_rec'] = df['no_analyst_rec'].fillna(df['no_analyst_rec'].mode().values[0])
df = df[~ df['no_analyst_rec'].isin(['0', ' ',])]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4525 entries, 0 to 4524
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name                         4525 non-null   object
 1   Ticker                       4525 non-null   object
 2   sub_sector                   4525 non-null   object
 3   market_cap                   4426 non-null   float64
 4   close_price                  4426 non-null   float64
 5   pe_ratio                     4426 non-null   float64
 6   5year_past_growth            4426 non-null   float64
 7   1year_future_growth          4426 non-null   float64
 8   total_revenue                4426 non-null   float64
 9   PBT                          4426 non-null   float64
 10  Taxes_others                 4426 non-null   float64
 11  dii_holding                  4426 non-null   float64
 12  fii_holding                  4426 non-null   float64
 13  mf_holding                   4426 non-null   float64
 14  promoter_holding             4426 non-null   float64
 15  percentage_buy               4426 non-null   float64
 16  no_analyst_rec               4525 non-null   int64
 17  percentage_upside            4426 non-null   float64
 18  pat                          4426 non-null   float64
 19  outstanding_shares           4426 non-null   float64
 20  eps                          4383 non-null   float64
 21  percentage_hold_by_promoter  4353 non-null   float64
 22  analyst_buy_ratio            761 non-null    float64
 23  roe                          4246 non-null   float64
 24  profit_margin                4246 non-null   object
 25  ps_ratio                     4379 non-null   float64
 26  retail_holding_change        4426 non-null   float64
dtypes: float64(22), int64(1), object(4)
memory usage: 989.8+ KB

In [ ]:

df['sub_sector'].unique()

array(['Oil & Gas - Refining & Marketing', 'IT Services & Consulting',
       'Private Banks', 'FMCG - Household Products', 'Public Banks',
       'Telecom Services', 'Home Financing', 'Commodities Trading',
       'FMCG - Tobacco', 'Consumer Finance', 'Insurance',
       'Gas Distribution', 'Renewable Energy', 'Power Infrastructure',
       'Paints', 'Construction & Engineering', 'Four Wheelers',
       'Retail - Department Stores', 'Pharmaceuticals', 'Precious Metals',
       'Cement', 'FMCG - Foods', 'Ports',
       'Oil & Gas - Exploration & Production', 'Iron & Steel',
       'Power Generation', 'Power Transmission & Distribution',
       'Mining - Coal', 'Diversified Chemicals', 'Mining - Diversified',
       'Metals - Diversified', 'Two Wheelers', 'FMCG - Personal Products',
       'Conglomerates', 'Real Estate', 'Metals - Aluminium',
       'Trucks & Buses', 'Aerospace & Defense Equipments',
       'Labs & Life Sciences Services', 'Electronic Equipments',
       'Soft Drinks', 'Payment Infrastructure',
       'Electrical Components & Equipments', 'Tea & Coffee', 'Airlines',
       'Asset Management', 'Hospitals & Diagnostic Centres',
       'Heavy Electrical Equipments', 'Alcoholic Beverages',
       'Fertilizers & Agro Chemicals', 'Online Services',
       'Telecom Infrastructure', 'Cycles', 'Apparel & Accessories',
       'Retail - Apparel', 'Wellness Services', 'Auto Parts', 'Logistics',
       'Hotels', 'Packaged Foods & Meats', 'Specialized Finance',
       'Software Services', 'Tires & Rubber', 'Specialty Chemicals',
       'Industrial Machinery', 'Building Products - Pipes',
       'Restaurants & Cafes', 'Mining - Iron Ore', 'Commodity Chemicals',
       'Biotechnology', 'Diversified Financials', 'Textiles',
       'Oil & Gas - Storage & Transportation', 'Plastic Products',
       'Business Support Services', 'Tractors',
       'Home Electronics & Appliances', 'Cables', 'Stationery',
       'TV Channels & Broadcasters', 'Footwear', 'Equity',
       'Stock Exchanges & Ratings', 'Investment Banking & Brokerage',
       'Building Products - Ceramics', 'Shipbuilding', 'Advertising',
       'Batteries', 'Technology Hardware', 'Power Trading & Consultancy',
       'Home Furnishing', 'Renewable Energy Equipment & Services',
       'Wood Products', 'Sugar', 'Tour & Travel Services', 'Theatres',
       'Mining - Copper', 'Telecom Equipments',
       'Health Care Equipment & Supplies', 'Agro Products',
       'Paper Products', 'Debt', 'Outsourced services',
       'Movies & TV Serials', 'Roads', 'Infra REIT',
       'Employment Services', 'Theme Parks & Gaming', 'Housewares',
       'Rail', 'Packaging', 'Gold', 'Communication & Networking',
       'Education Services', 'Building Products - Laminates',
       'Building Products - Granite', 'Heavy Machinery', 'Cable & D2H',
       'Environmental Services', 'Mining - Manganese', 'Seeds',
       'Publishing', 'Animation', 'Metals - Lead',
       'Oil & Gas - Equipment & Services',
       'Agricultural & Farm Machinery', 'Water Management',
       'Retail - Speciality', 'Dredging',
       'Building Products - Prefab Structures', 'Radio', 'Three Wheelers',
       'Metals - Coke', 'Building Products - Glass', 'Airports',
       'Retail - Online', 'Metals - Iron', 'Metals - Copper',
       'Academic & Educational Services'], dtype=object)

In [ ]:
df['sub_sector'] = df['sub_sector'].fillna(df['sub_sector'].mode().values[0])
df = df[~ df['sub_sector'].isin(['0', ' ',])]
df['sub_sector'].unique()

array(['Oil & Gas - Refining & Marketing', 'IT Services & Consulting',
       'Private Banks', 'FMCG - Household Products', 'Public Banks',
       'Telecom Services', 'Home Financing', 'Commodities Trading',
       'FMCG - Tobacco', 'Consumer Finance', 'Insurance',
       'Gas Distribution', 'Renewable Energy', 'Power Infrastructure',
       'Paints', 'Construction & Engineering', 'Four Wheelers',
       'Retail - Department Stores', 'Pharmaceuticals', 'Precious Metals',
       'Cement', 'FMCG - Foods', 'Ports',
       'Oil & Gas - Exploration & Production', 'Iron & Steel',
       'Power Generation', 'Power Transmission & Distribution',
       'Mining - Coal', 'Diversified Chemicals', 'Mining - Diversified',
       'Metals - Diversified', 'Two Wheelers', 'FMCG - Personal Products',
       'Conglomerates', 'Real Estate', 'Metals - Aluminium',
       'Trucks & Buses', 'Aerospace & Defense Equipments',
       'Labs & Life Sciences Services', 'Electronic Equipments',
       'Soft Drinks', 'Payment Infrastructure',
       'Electrical Components & Equipments', 'Tea & Coffee', 'Airlines',
       'Asset Management', 'Hospitals & Diagnostic Centres',
       'Heavy Electrical Equipments', 'Alcoholic Beverages',
       'Fertilizers & Agro Chemicals', 'Online Services',
       'Telecom Infrastructure', 'Cycles', 'Apparel & Accessories',
       'Retail - Apparel', 'Wellness Services', 'Auto Parts', 'Logistics',
       'Hotels', 'Packaged Foods & Meats', 'Specialized Finance',
       'Software Services', 'Tires & Rubber', 'Specialty Chemicals',
       'Industrial Machinery', 'Building Products - Pipes',
       'Restaurants & Cafes', 'Mining - Iron Ore', 'Commodity Chemicals',
       'Biotechnology', 'Diversified Financials', 'Textiles',
       'Oil & Gas - Storage & Transportation', 'Plastic Products',
       'Business Support Services', 'Tractors',
       'Home Electronics & Appliances', 'Cables', 'Stationery',
       'TV Channels & Broadcasters', 'Footwear', 'Equity',
       'Stock Exchanges & Ratings', 'Investment Banking & Brokerage',
       'Building Products - Ceramics', 'Shipbuilding', 'Advertising',
       'Batteries', 'Technology Hardware', 'Power Trading & Consultancy',
       'Home Furnishing', 'Renewable Energy Equipment & Services',
       'Wood Products', 'Sugar', 'Tour & Travel Services', 'Theatres',
       'Mining - Copper', 'Telecom Equipments',
       'Health Care Equipment & Supplies', 'Agro Products',
       'Paper Products', 'Debt', 'Outsourced services',
       'Movies & TV Serials', 'Roads', 'Infra REIT',
       'Employment Services', 'Theme Parks & Gaming', 'Housewares',
       'Rail', 'Packaging', 'Gold', 'Communication & Networking',
       'Education Services', 'Building Products - Laminates',
       'Building Products - Granite', 'Heavy Machinery', 'Cable & D2H',
       'Environmental Services', 'Mining - Manganese', 'Seeds',
       'Publishing', 'Animation', 'Metals - Lead',
       'Oil & Gas - Equipment & Services',
       'Agricultural & Farm Machinery', 'Water Management',
       'Retail - Speciality', 'Dredging',
       'Building Products - Prefab Structures', 'Radio', 'Three Wheelers',
       'Metals - Coke', 'Building Products - Glass', 'Airports',
       'Retail - Online', 'Metals - Iron', 'Metals - Copper',
       'Academic & Educational Services'], dtype=object)

In [ ]:
#Below code is for the calculation of ratios
df['pat'] = df['PBT'] - df['Taxes_others']
df['outstanding_shares'] = df['market_cap'] - df['pat']
df['eps'] = df['pat'] / df['outstanding_shares']
df['percentage_hold_by_promoter'] = (df['promoter_holding'] / df['close_price']) * 100
df['analyst_buy_ratio'] = (df['no_analyst_rec'] / df['percentage_buy']) * 100
df['roe'] = df['pat'] / (df['total_revenue'] - df['pat']) * 100
df['profit_margin'] = (df['pat'] / df['total_revenue']) * 100
df['ps_ratio'] = df['market_cap'] / df['total_revenue']
df['retail_holding_change'] = -(df['dii_holding'] + df['fii_holding'] + df['mf_holding'] + df['promoter_holding'])

In [ ]:
#Below code is to round off the values
df['pat'] = df['pat'].round(2)
df['eps'] = df['eps'].round(2)
df['analyst_buy_ratio'] = df['analyst_buy_ratio'].round(2)
df['roe'] = df['roe'].round(2)
df['percentage_hold_by_promoter'] = df['percentage_hold_by_promoter'].round(2)
df['profit_margin'] = df['profit_margin'].round(2)

In [ ]:
#Below code is to convert this file into csv to import it into the POWER BI Desktop for visualization
df.to_csv('/content/gm_100_samarth.csv', index=False)